In [52]:
import pandas as pd
import numpy as np

In [53]:
data = { "Car"   : ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],
         "Color" : ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],
         "Year"  : ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],
         "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],
         "Date"  : ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",
                   "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df = pd.DataFrame(data)
df.head()

      Car   Color  Year Rating        Date
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      object
dtypes: object(5)
memory usage: 452.0+ bytes

In [55]:
df['Date']=pd.to_datetime(df['Date'],dayfirst=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 452.0+ bytes

In [56]:
df['year']=df['Date'].dt.year

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      datetime64[ns]
 5   year    8 non-null      int32
dtypes: datetime64[ns](1), int32(1), object(4)
memory usage: 484.0+ bytes

In [58]:
#let us create month colunm
df['month']=df['Date'].dt.month
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      datetime64[ns]
 5   year    8 non-null      int32
 6   month   8 non-null      int32
dtypes: datetime64[ns](1), int32(2), object(4)
memory usage: 516.0+ bytes

In [59]:
df["day"]=df['Date'].dt.day

In [60]:
df.head()

      Car   Color  Year Rating       Date  year  month  day
0     BMW     Red  1990    2.5 2023-04-30  2023      4   30
1    ALTO  Yellow  1980    1.5 1999-08-31  1999      8   31
2    AUDI   Black  2003    3.8 2015-12-28  2015     12   28
3  MARUTI   Green  2000    9.7 2011-06-29  2011      6   29
4   HONDA   Black  2001    8.9 2020-12-30  2020     12   30

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      datetime64[ns]
 5   year    8 non-null      int32
 6   month   8 non-null      int32
 7   day     8 non-null      int32
dtypes: datetime64[ns](1), int32(3), object(4)
memory usage: 548.0+ bytes

 # date_range()

In [68]:
# Day wise
pd.date_range("04/07/2026",periods=7)

DatetimeIndex(['2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10',
               '2026-04-11', '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [69]:
x=pd.date_range("04/07/2026",periods=7)
print(x)
print(type(x))
y=pd.Series(x)
print(y)

DatetimeIndex(['2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10',
               '2026-04-11', '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
0   2026-04-07
1   2026-04-08
2   2026-04-09
3   2026-04-10
4   2026-04-11
5   2026-04-12
6   2026-04-13
dtype: datetime64[ns]

In [76]:
#month wise
print(pd.date_range('04/08/2026',periods=5,freq ='ME'))

DatetimeIndex(['2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31',
               '2026-08-31'],
              dtype='datetime64[ns]', freq='ME')

In [77]:
#year wise
print(pd.date_range("04/08/2026",periods=6,freq='YS'))

DatetimeIndex(['2027-01-01', '2028-01-01', '2029-01-01', '2030-01-01',
               '2031-01-01', '2032-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [78]:
#year wise
print(pd.date_range("04/08/2026",periods=6,freq='YS'))

DatetimeIndex(['2027-01-01', '2028-01-01', '2029-01-01', '2030-01-01',
               '2031-01-01', '2032-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [83]:
start=pd.to_datetime('2026-04-08')
print(f"Start:{start}")

end=pd.to_datetime('2026-05-08')
print(f'End:{end}')

pd.date_range(start,end)
print(x)
x.size

Start:2026-04-08 00:00:00
End:2026-05-08 00:00:00
DatetimeIndex(['2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10',
               '2026-04-11', '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

7

In [86]:
df = pd.DataFrame({
    "name" : ["MSD","Virat", "Rohith"],
    "DoB" : ["07-07-1981", "11-05-1988", "04-30-1987"]
})
df.head()

     name         DoB
0     MSD  07-07-1981
1   Virat  11-05-1988
2  Rohith  04-30-1987

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   DoB     3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [91]:
df["DoB"]=pd.to_datetime(df["DoB"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   DoB     3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

In [90]:
df.head()

     name        DoB
0     MSD 1981-07-07
1   Virat 1988-11-05
2  Rohith 1987-04-30

In [92]:
df["Year"]=df["DoB"].dt.year

In [94]:
df["Month"]=df["DoB"].dt.month

In [95]:
df["Day"]=df['DoB'].dt.day

In [96]:
df.head()

     name        DoB  Year  Month  Day
0     MSD 1981-07-07  1981      7    7
1   Virat 1988-11-05  1988     11    5
2  Rohith 1987-04-30  1987      4   30

In [97]:
df["day_name"]=df['DoB'].dt.day_name()

In [98]:
df

     name        DoB  Year  Month  Day  day_name
0     MSD 1981-07-07  1981      7    7   Tuesday
1   Virat 1988-11-05  1988     11    5  Saturday
2  Rohith 1987-04-30  1987      4   30  Thursday

In [99]:
df["Month_name"]=df['DoB'].dt.month_name()

In [100]:
df

     name        DoB  Year  Month  Day  day_name Month_name
0     MSD 1981-07-07  1981      7    7   Tuesday       July
1   Virat 1988-11-05  1988     11    5  Saturday   November
2  Rohith 1987-04-30  1987      4   30  Thursday      April

In [103]:
df["week_day"]=df["DoB"].dt.weekday

In [104]:
df

     name        DoB  Year  Month  Day  day_name Month_name  week_day
0     MSD 1981-07-07  1981      7    7   Tuesday       July         1
1   Virat 1988-11-05  1988     11    5  Saturday   November         5
2  Rohith 1987-04-30  1987      4   30  Thursday      April         3

In [106]:
#checking the present year
today=pd.to_datetime('today')
today

Timestamp('2026-04-30 12:20:50.266495')

In [107]:
today.year

2026

In [108]:
today.month

4

In [109]:
today.week

18

In [111]:
today.weekday()

3

In [113]:
today.month_name()

'April'

In [114]:
df

     name        DoB  Year  Month  Day  day_name Month_name  week_day
0     MSD 1981-07-07  1981      7    7   Tuesday       July         1
1   Virat 1988-11-05  1988     11    5  Saturday   November         5
2  Rohith 1987-04-30  1987      4   30  Thursday      April         3

In [115]:
# age =current year-->date of Birth
df["Age"]=today.year-df["DoB"].dt.year

In [117]:
df

     name        DoB  Year  Month  Day  day_name Month_name  week_day  Age
0     MSD 1981-07-07  1981      7    7   Tuesday       July         1   45
1   Virat 1988-11-05  1988     11    5  Saturday   November         5   38
2  Rohith 1987-04-30  1987      4   30  Thursday      April         3   39

In [ ]:
#